---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
data:
  POSTGRES_DB: testdatabase
  #POSTGRES_PASSWORD: testpassword
  POSTGRES_USER: testuser
  PGDATA: /var/lib/postgresql/data/pgdata
  