---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrs  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:      
      containers:
      - image: postgres:10.13
        name: postgres
        ports:
          - containerPort: 5432
        envFrom:
          configMap:
            name: postgres
          secret:
            name: psecret
        volumeMounts:
          name: postgres-pvc
          mountPath: /var/lib/postgresql/data
    volumes:
        name: postgres-pvc
        persistentVolumeClaim:
          claimName: pvc
